---
title: "Visualization 1"
author: Alison Elgass
output: github_document
---
```{r}
library(tidyverse)
library(ggridges)
```

# Some basic examples
```{r}
#THIS WILL TAKE A WHILE
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728",
                               "USC00519397",
                               "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>% 
  
  mutate(name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
       tmin = tmin / 10,
       tmax = tmax / 10) %>% 
  
  select(name, id, everything())
```


```{r}
#Basic scatter plot of min vs. max temp
ggplot(weather_df, aes(x = tmin, y = tmax)) + geom_point()

#Another way to write, with piping
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

#Another way to write (save plot as a variable)
plot_weather = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) 

plot_weather + geom_point()

```

```{r}
#Add color to code variable 'name', auto adds legend
#note color is within point aesthetics
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))

```

```{r}
#Add a smooth curve using 'geom_smooth'
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  geom_smooth(se = FALSE)
```

```{r}
#Create 3 separate charts by name using facets
#note color now goes in overall aesthetics
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(~name)
```

```{r}
#Graph date vs. max temp
#Size of point = precip level
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp)) +
  geom_smooth(size = 2, se = FALSE)
```

## Some more examples
```{r}
#Just smooth curves
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_smooth(size = 2, se = FALSE)

#2D Density using 'bin2d'
ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_bin2d()

#Split that up into panels
ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_bin2d() +
  facet_grid(~name)
```

## Histograms!
```{r}
#The humble histogram...
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram()

#Put each bar next to each other instead of on time
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram(position = "dodge", binwidth = 2)

#split into 3 panels
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram() +
  facet_grid(~name)
```

## Density Plots!!
```{r}
weather_df %>% 
ggplot(aes(x = tmax, fill = name)) + 
  geom_density(alpha = .4, adjust = .5, color = "blue")
```

## Boxplots!!!
```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()
```

## Ridge Plots
```{r}
ggplot(weather_df, aes(x = tmax, y = name)) + 
  geom_density_ridges(scale = .85)
```

# Saving & Exporting
```{r}
#Save this plot as a variable first
ridge_plot = ggplot(weather_df, aes(x = tmax, y = name)) + 
  geom_density_ridges(scale = .85)

ggsave("ggplot_ridge.pdf", ridge_plot)
```

## Embedding plots in R Markdown
Pay attention to figure width in code chunk options!!
```{r fig.width=6}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  geom_smooth(se = FALSE)
```

```{r fig.width=12}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  geom_smooth(se = FALSE)
```
 
